// Code generated by "stringer -linecomment -output scalars_string.go -type BinarySubtype"; DO NOT EDIT.

package bson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinaryGeneric-0]
	_ = x[BinaryFunction-1]
	_ = x[BinaryBinaryOld-2]
	_ = x[BinaryUUIDOld-3]
	_ = x[BinaryUUID-4]
	_ = x[BinaryMD5-5]
	_ = x[BinaryEncrypted-6]
	_ = x[BinaryCompressed-7]
	_ = x[BinaryUser-128]
}

const (
	_BinarySubtype_name_0 = "genericfunctionbinary-olduuid-olduuidmd5encryptedcompressed"
	_BinarySubtype_name_1 = "user"
)

var (
	_BinarySubtype_index_0 = [...]uint8{0, 7, 15, 25, 33, 37, 40, 49, 59}
)

func (i BinarySubtype) String() string {
	switch {
	case i <= 7:
		return _BinarySubtype_name_0[_BinarySubtype_index_0[i]:_BinarySubtype_index_0[i+1]]
	case i == 128:
		return _BinarySubtype_name_1
	default:
		return "BinarySubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
